<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Orynivo/Localization/Strings.cs" Link="Strings.cs" />
    <Compile Include="../../Orynivo/Localization/Language.cs" Link="Language.cs" />
    <Compile Include="../../Orynivo/Localization/LocalizationManager.cs" Link="LocalizationManager.cs" />
  </ItemGroup>
</Project>
